
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      format_sql: true
      show_sql: true
      hibernate:
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    database-platform: MySQL

logging:
  level:
    #    org.hibernate.sql: debug
    org.hibernate.sql: info
    org.hibernate.jdbc.bind: trace

